#!/usr/bin/env bash
# Create the local ALPR virtualenv and install inference dependencies.
#
# Run it through the pinned interpreter so binary wheels find their libraries:
#   nix-shell python-alpr-local/shell.nix --run python-alpr-local/setup.sh
#
# Pass --train to also install the training-only dependencies.
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$BASE_DIR/.venv"

REQ="$BASE_DIR/requirements.txt"
if [[ "${1:-}" == "--train" ]]; then
    REQ="$BASE_DIR/requirements-train.txt"
fi

if [[ ! -x "$VENV/bin/python" ]]; then
    echo ">> creating venv at $VENV"
    python3.12 -m venv "$VENV"
fi

echo ">> installing $(basename "$REQ")"
"$VENV/bin/python" -m pip install --upgrade pip
"$VENV/bin/python" -m pip install -r "$REQ"

# The wheels are prebuilt for generic Linux, so their .so files need the nix
# store paths that shell.nix put on LD_LIBRARY_PATH. A process started outside
# that shell -- the router spawning the CLI, for example -- has no such path and
# fails with "OpenCV bindings requires numpy". Freeze the value into a wrapper
# so the interpreter works no matter who launches it.
echo ">> writing interpreter wrapper"
cat > "$BASE_DIR/run-python" <<WRAPPER
#!/usr/bin/env bash
# Generated by setup.sh -- do not edit. Runs the ALPR venv interpreter with the
# native library paths its binary wheels need.
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"
exec "$VENV/bin/python" "\$@"
WRAPPER
chmod +x "$BASE_DIR/run-python"

echo ">> verifying"
"$BASE_DIR/run-python" - <<'PY'
import onnxruntime, cv2, numpy
print(f"onnxruntime {onnxruntime.__version__}, opencv {cv2.__version__}, numpy {numpy.__version__}")
try:
    import fast_alpr
    print("fast_alpr OK")
except ImportError as e:
    print(f"fast_alpr unavailable: {e}")
PY
